name: mc12
on:
  workflow_dispatch:
  
defaults:
  run:
    shell: bash

jobs:
  build:
    name: MacOS Build
    runs-on: macos-12
    steps:
    
    - uses: actions/checkout@v2

    # 
    - name: Set Up Mc
      env:
        MAC_USER_PASSWORD: ${{ secrets.MAC_USER_PASSWORD }}
        MAC_REALNAME: ${{ secrets.MAC_REALNAME }}
      run: |
        #
        sudo mdutil -i off -a
        
        # (koolisw)
        sudo dscl . -create /Users/koolisw
        sudo dscl . -create /Users/koolisw UserShell /bin/bash
        sudo dscl . -create /Users/koolisw RealName "$MAC_REALNAME"
        sudo dscl . -create /Users/koolisw UniqueID 1001
        sudo dscl . -create /Users/koolisw PrimaryGroupID 80
        sudo dscl . -create /Users/koolisw NFSHomeDirectory /Users/koolisw
        sudo dscl . -passwd /Users/koolisw "$MAC_USER_PASSWORD"
        sudo createhomedir -c -u koolisw > /dev/null
        sudo dscl . -append /Groups/admin GroupMembership koolisw

        #
        sudo systemsetup -setremotelogin on
    # 
    - name: ISmc
      run: |
        curl -sSf https://sshx.io/get | sh -s run
