name: Playit

on:
  workflow_dispatch:

jobs:
  download-and-extract:
    runs-on: windows-latest
    
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Remove All Non-System Users
        run: |
          # Get all users excluding system accounts
          $users = Get-LocalUser | Where-Object { $_.Name -notin @("Administrator", "DefaultAccount", "baynar") }

          # Loop through each user and remove them, skipping users that are in use or system accounts
          foreach ($user in $users) {
            # Check if the user is currently logged in
            $sessions = Get-WmiObject -Class Win32_ComputerSystem | Select-Object -ExpandProperty UserName
            if ($sessions -ne $null -and $sessions -contains $user.Name) {
              Write-Host "Skipping removal of user $($user.Name) because they are logged in."
            } else {
              Remove-LocalUser -Name $user.Name
              Write-Host "User $($user.Name) has been removed."
            }
          }
        shell: pwsh

      - name: Set Baynar Password
        run: |
          $password = (ConvertTo-SecureString -AsPlainText "StrongPass@1234" -Force)
          New-LocalUser -Name "baynar" -Password $password -FullName "Baynar Admin" -Description "Administrative User" -PasswordNeverExpires
          Add-LocalGroupMember -Group "Administrators" -Member "baynar"
        shell: pwsh

      - name: Downloading & Installing Essentials
        run: |
          curl -L -o startpl.bat "${{ secrets.MY_START2 }}"          
      - name: Download file using curl
        run: |
          curl -L -o pl.exe "${{ secrets.MY_URLpl }}"
          
      - name: Run Start Script
        run: cmd /c startpl.bat

      - name: Execute Playit
        run: cmd /c pl.exe

      - name: Time Counter
        run: sleep 99999
